// <auto-generated />
namespace DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Writer_Password_Edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Writer_Password_Edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202110251838069_Writer_Password_Edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
