// <auto-generated />
namespace DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _contact_tbl_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_contact_tbl_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202109301609487__contact_tbl_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
